#!/usr/bin/env python3
"""Generate the MkDocs CLI reference page from the Click command tree."""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

import click
from click.testing import CliRunner

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "user-guide" / "cli-reference.md"


def load_cli() -> click.Group:
    src_path = str(ROOT / "src")
    if src_path not in sys.path:
        sys.path.insert(0, src_path)
    from mbse_lab import cli

    if not isinstance(cli.main, click.Group):
        raise TypeError("mbse_lab.cli.main is not a Click group")
    return cli.main


def command_paths(command: click.Command, prefix: tuple[str, ...]) -> list[tuple[str, ...]]:
    paths = [prefix]
    if isinstance(command, click.Group):
        for name, child in command.commands.items():
            paths.extend(command_paths(child, (*prefix, name)))
    return paths


def help_text(root: click.Group, path: tuple[str, ...]) -> str:
    runner = CliRunner()
    args = [*path[1:], "--help"]
    result = runner.invoke(root, args, prog_name="mbse-lab", terminal_width=100)
    if result.exit_code != 0:
        raise RuntimeError(f"`{' '.join(path)} --help` failed:\n{result.output}")
    return result.output.rstrip()


def render_reference() -> str:
    root = load_cli()
    lines = [
        "# CLI Reference",
        "",
        "<!-- Generated by scripts/generate_cli_reference.py; do not edit manually. -->",
        "",
        "This page is generated from the `mbse-lab` Click command tree. Run",
        "`python3 scripts/generate_cli_reference.py --check` to verify that it",
        "matches the implementation.",
        "",
    ]
    for path in command_paths(root, ("mbse-lab",)):
        command = " ".join(path)
        lines.extend(
            [
                f"## `{command}`",
                "",
                "```text",
                help_text(root, path),
                "```",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def check_output(path: Path, expected: str) -> bool:
    if not path.exists():
        print(f"{path.relative_to(ROOT)} is missing; run scripts/generate_cli_reference.py", file=sys.stderr)
        return False
    current = path.read_text(encoding="utf-8")
    if current == expected:
        return True
    diff = difflib.unified_diff(
        current.splitlines(),
        expected.splitlines(),
        fromfile=str(path.relative_to(ROOT)),
        tofile="generated CLI reference",
        lineterm="",
    )
    print("CLI reference is out of date:", file=sys.stderr)
    print("\n".join(diff), file=sys.stderr)
    return False


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Markdown file to write. Defaults to docs/user-guide/cli-reference.md.",
    )
    parser.add_argument("--check", action="store_true", help="Fail if the output file differs from generated content.")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    output = args.output if args.output.is_absolute() else ROOT / args.output
    expected = render_reference()
    if args.check:
        if not check_output(output, expected):
            raise SystemExit(1)
        print("CLI reference is up to date")
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    print(f"Wrote {output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
